site_name: Tonis
site_author: Kyle Spraggs
copyright: 2015 Kyle Spraggs. All Rights Reserved.
site_url: http://tonis.io
repo_url: https://github.com/tonis-io/tonis/
theme: readthedocs
pages:
- What is Tonis?: 'index.md'
- Getting Started:
  - 'Installation': 'getting-started/installation.md'
  - 'Contributing': 'getting-started/contributing.md'
  - 'License': 'getting-started/license.md'
- Basics:
  - 'Configuration': 'basics/configuration.md'
  - 'Routing': 'basics/routing.md'
  - 'Dispatching': 'basics/dispatching.md'
  - 'Views': 'basics/views.md'
  - 'Services': 'basics/services.md'
  - 'Packages': 'basics/packages.md'
- Advanced Topics:
  - 'Middleware': 'advanced/middleware.md'
  - 'Request/Response Lifecycle': 'advanced/lifecycle.md'
- Development:
  - 'Vagrant': 'development/vagrant.md'
  - 'Docker': 'development/docker.md'
- Other:
  - 'Components & Packages': 'other/components-and-packages.md'
